Compile minimal library:
  script:
  - git submodule update --init && make autoreconf && ./configure --with-included-libtasn1
    --disable-doc --disable-dtls-srtp-support --disable-alpn-support --disable-rsa-export
    --disable-heartbeat-support --disable-srp-authentication --disable-psk-authentication
    --disable-anon-authentication --disable-dhe --disable-ecdhe --disable-openpgp-authentication
    --disable-ocsp --disable-session-tickets --disable-openssl-compatibility --disable-non-suiteb-curves
    --disable-nls --disable-crywrap --disable-libdane --without-p11-kit --without-tpm
    --without-zlib --disable-doc --disable-tests && make -j4
  tags:
  - x86-64
  - nettle3
  except:
  - tags
Build and Check with valgrind:
  script:
  - git submodule update --init && make autoreconf && ./configure
    --disable-non-suiteb-curves --with-included-libtasn1 --disable-doc && make -j4 && make check -j4
  - cat tests/test-suite.log
  tags:
  - x86-64
  - nettle3
  except:
  - tags
Build and Check with asan:
  script:
  - git submodule update --init && make autoreconf &&CFLAGS="-fsanitize=address -g
    -O2" LDFLAGS="-static-libasan" ./configure --disable-doc --with-included-libtasn1 --disable-valgrind-tests --disable-non-suiteb-curves --disable-guile
    && make -j4 && make check -j4
  - cat tests/test-suite.log
  tags:
  - x86-64
  - nettle3
  except:
  - tags
Build and Check - separate build dir (x86-64):
  script:
  - git submodule update --init && make autoreconf && mkdir -p build && cd build && ../configure
    --disable-non-suiteb-curves --with-included-libtasn1 --enable-seccomp-tests --disable-valgrind-tests --disable-doc && make -j4 && make check -j4
  - cat tests/test-suite.log
  tags:
  - x86-64
  - nettle3
  except:
  - tags
Build and Check - separate build dir (x86):
  script:
  - git submodule update --init && make autoreconf && mkdir -p build && cd build &&
    ../configure --disable-non-suiteb-curves --with-included-libtasn1 --enable-seccomp-tests --disable-doc --disable-valgrind-tests &&
    make -j4 && make check -j4
  - cat tests/test-suite.log
  tags:
  - x86
  - nettle3
  except:
  - tags
